version: '3.8'

services: 
  postgres:
    image: postgres:latest
    container_name: postgres_local
    environment: 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PWD} 
      POSTGRES_DB: ${POSTGRES_DBNAME} 
    ports:
      - "${POSTGRES_PORT}:5432" # Map local:container
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    networks:
      - my_network
volumes:
  postgres_data:

networks:
  my_network: