from sqlalchemy import Column, Integer, String, ARRAY, Text, CheckConstraint, Date, Numeric
from models.base import Base

class CoinmetricDaily(Base):
    __tablename__ = 'coinmetric_daily'
    __table_args__ = (
        CheckConstraint('char_length(asset_symbol) > 3', name='check_symbol_length'),
        {'extend_existing': True}
    )  

    uniq_key = Column(String, primary_key=True) # uniqkey gen by asset_symbol, time
    asset_symbol = Column(String, nullable=False)
    time = Column(Date, nullable=False)
    AdrActCnt=Column(Numeric)
    CapAct1yrUSD=Column(Numeric)
    CapMVRVCur=Column(Numeric)
    CapMVRVFF=Column(Numeric)
    CapMrktCurUSD=Column(Numeric)
    CapMrktEstUSD=Column(Numeric)
    CapMrktFFUSD=Column(Numeric)
    CapRealUSD=Column(Numeric)
    FeeMeanNtv=Column(Numeric)
    FeeMeanUSD=Column(Numeric)
    FeeMedNtv=Column(Numeric)
    FeeMedUSD=Column(Numeric)
    FeeTotNtv=Column(Numeric)
    FeeTotUSD=Column(Numeric)
    PriceBTC=Column(Numeric)
    PriceUSD=Column(Numeric)
    SplyFF=Column(Numeric)
    SplyCur=Column(Numeric)
    TxCnt=Column(Numeric)
    TxTfrCnt=Column(Numeric)
    TxTfrValAdjNtv=Column(Numeric)
    TxTfrValAdjUSD=Column(Numeric)
    TxTfrValMeanNtv=Column(Numeric)
    TxTfrValMeanUSD=Column(Numeric)
    TxTfrValMedNtv=Column(Numeric)
    TxTfrValMedUSD=Column(Numeric)
    SER=Column(Numeric)
    AdrBalUSD100Cnt=Column(Numeric)
    AdrBalUSD1KCnt=Column(Numeric)
    AdrBalUSD10KCnt=Column(Numeric)
    AdrBalUSD100KCnt=Column(Numeric)
    AdrBalUSD1MCnt=Column(Numeric)
    SplyAdrBalUSD100=Column(Numeric)
    SplyAdrBalUSD1K=Column(Numeric)
    SplyAdrBalUSD10K=Column(Numeric)
    SplyAdrBalUSD100K=Column(Numeric)
    SplyAdrBalUSD1M=Column(Numeric)
    SplyAct1d=Column(Numeric)
    SplyAct30d=Column(Numeric)
    SplyAct1yr=Column(Numeric)
    SplyAct90d=Column(Numeric)
    VtyDayRet30d=Column(Numeric)