from sqlalchemy import Column, Integer, String, ARRAY, Text, CheckConstraint, Date, Numeric
from models.base import Base

class CoinmetricData(Base):
    __tablename__ = 'coinmetric_historical_data'
    __table_args__ = (
        CheckConstraint('char_length(asset_symbol) > 3', name='check_symbol_length'),
        {'extend_existing': True}
    )  

    uniq_key = Column(Integer, primary_key=True) # unique key generated by asset, metric_date
    metric_date = Column(Date)
    asset_symbol = Column(String, nullable=False)
    

    